[project]
drom-version = "0.1"

[project]
authors = ["Julien BLOND <julien.blond@bertin.fr>"]
ci-systems = ["ubuntu-latest", "macos-latest", "windows-latest"]
copyright = "Julien BLOND <julien.blond@bertin.fr>"
edition = "4.10.0"
license = "LGPL2"
min-edition = "4.07.0"
name = "openapi"
synopsis = "The openapi project"
version = "0.1.0"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# dev-repo = "...dev-repo..."
# bug-reports = "...bug-reports..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."
# github-organization = "...github-organization..."

[project]
description = """\n
This is the description
of the openapi OCaml project
"""

[project]
skip = "src/openapi/main.ml"

# project-wide library dependencies (not for package-specific deps)
[dependencies]

# project-wide tools dependencies (not for package-specific deps)
[tools.ocamlformat]
for-test = true
[tools.odoc]
for-doc = true
[tools.ppx_expect]
for-test = true
[tools.ppx_inline_test]
for-test = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = []

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
# ...

# project-wide fields (depends on project skeleton)
[fields]
# ...

[[package]]
dir = "src/openapi"
# edit 'src/openapi/package.toml' for package-specific options

